---
title: "Demo Plots"
author: "Z. Love"
date: "2022-12-15"
output: html_document
---

```{r}
ICU_df |>
  group_by(gender) |>
  count() |>
  ggplot(aes(x = "", y = n, fill = gender)) + 
  geom_col() + 
  coord_polar(theta ="y") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.background = element_rect(fill = "#ebf2ff"))

```

```{r}
ICU_df |>
  group_by(race) |>
  count() |>
  ggplot(aes(x = "", y=n, fill = race)) +
  geom_col() + 
  coord_polar(theta ="y") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.background = element_rect(fill = "#ebf2ff"),
        legend.position = "bottom",
        legend.text = element_text(size=5),
        legend.key.size = unit(0.2, "cm"))
```
```{r}


ICU_age <- ICU_df |>
  mutate(age_group = cut(ICU_df$admission_age, c(18, 29, 39, 49, 59, 69, 79, 90, Inf), c("18-29","30-39","40-49","50-59","60-69", "70-79", "80-90", ">90"), include.lowest=TRUE))

ICU_age |>
  group_by(age_group) |>
  count() |>
  ggplot(aes(x = "", y = n, fill = age_group)) + 
  geom_col() + 
  coord_polar(theta ="y") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.background = element_rect(fill = "#ebf2ff"))
  

```






